name: ALVRClient
options:
  bundleIdPrefix: com.Aed
targets:
  ALVRClient:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: 
      - path: ALVRClient/main
      # Add the bridging header to the sources so XcodeGen tracks it
      - path: ALVRClient/ALVRClient-Bridging-Header.h
    frameworks:
      - framework: ALVRClientCore.xcframework
      - sdk: ARKit.framework
      - sdk: Vision.framework
    settings:
      base:
        INFOPLIST_FILE: ALVRClient/Info.plist
        # THIS IS THE CRITICAL FIX:
        SWIFT_OBJC_BRIDGING_HEADER: ALVRClient/ALVRClient-Bridging-Header.h
        # Tells the compiler to look in the project root for alvr_client_core.h
        HEADER_SEARCH_PATHS: $(inherited) $(PROJECT_DIR)
        FRAMEWORK_SEARCH_PATHS: $(inherited) $(PROJECT_DIR)
        LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks
        OTHER_LDFLAGS: $(inherited) -ObjC
